### DISCUSSION TITLE
Probably some CORS Problems

### DISCUSSION THREAD

**Discussion by Lukako94** [evroon/bracket#1240] [Q&A]
Hello Dear Community,

I'am trying to setup bracket for hours at the moment, and getting stuck at CORS. I'am a beginner on Docker etc and tried to get through this with help of ChatGPT but at this Point this is getting to complex somehow i guess.

Scenario:
Local Network Server with Debian Headless installed. 
No Internet reachability planned just hosted in local network.

My docker-compose.yaml looks like this:

 ```
services:

  bracket-frontend:
    image: ghcr.io/evroon/bracket-frontend
    container_name: bracket-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "DEVELOPMENT"
      NEXT_PUBLIC_API_BASE_URL: "http://192.168.1.217:8400"
      NEXT_PUBLIC_HCAPTCHA_SITE_KEY: ""
    restart: unless-stopped

  bracket-backend:
    image: ghcr.io/evroon/bracket-backend
    container_name: bracket-backend
    ports:
      - "8400:8400"
    environment:
      ENVIRONMENT: "DEVELOPMENT"
      PG_DSN: "postgresql://bracket_prod:bracket_prod@postgres:5432/bracket_prod"
      CORS_ORIGINS: "http://192.168.1.217:3000"
      JWT_SECRET: +SECRET+
    volumes:
      - ./backend/static:/app/static
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bracket_prod
      POSTGRES_USER: bracket_prod
      POSTGRES_PASSWORD: bracket_prod
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
```

MY prod.env

```
PG_DSN='postgresql://bracket_prod:bracket_prod@localhost:5532/bracket_prod'
JWT_SECRET= #SECRET#
CORS_ORIGINS='http://192.168.1.217:3000'
CORS_ORIGIN_REGEX='^http:\/\/192\.168\.1\.217(:[0-9]+)?$'
ADMIN_EMAIL='Mail'
ADMIN_PASSWORD='Password'
AUTO_RUN_MIGRATIONS=false
```

MY .env.local

```
NEXT_PUBLIC_HCAPTCHA_SITE_KEY=''
NEXT_PUBLIC_API_BASE_URL='http://192.168.1.217:8080'
ANALYTICS_SCRIPT_SRC=''
ANALYTICS_DATA_DOMAIN=''
ANALYTICS_DATA_WEBSITE_ID=''
```

Problem 1:
I cant Login with the user specified in .prod.env but with the User from Quickstart

Problem 2:
Looking in the console from browser while trying to delete an Tournament i'am getting CORS problems everything else just working fine.

Access to XMLHttpRequest at 'http://192.168.1.217:8400/tournaments/1' from origin 'http://192.168.1.217:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I cant find where to FIX that. Probably a stupid mistake. Sorry in advance.

Cheers
