### DISCUSSION TITLE
Installation problem

### DISCUSSION THREAD

**Discussion by Azurz** [evroon/bracket#693] [Q&A]
Hello,

I installed with Docker Compose, but I can't log in to the web console. I get this error.
POST http://localhost:8400/token net::ERR_CONNECTION_REFUSED

**Comment by robigan** [comment]
Provide docker compose configuration and more details.
> POST http://localhost:8400/token net::ERR_CONNECTION_REFUSED

Where? Doing what? From the fronted? Is this what shows in the notification error (if from frontend) or some sort of console?

**Comment by Azurz** [comment]
```
Docker-compose.yml
version: '3.1'

services:
    bracket-frontend:
        image: ghcr.io/evroon/bracket-frontend
        container_name: bracket-frontend
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_BASE_URL: "http://localhost:8400"
            NEXT_PUBLIC_HCAPTCHA_SITE_KEY: "10000000-ffff-ffff-ffff-000000000001"  # Public test key
        restart: unless-stopped

    bracket-backend:
        image: ghcr.io/evroon/bracket-backend
        container_name: bracket-backend
        ports:
            - "8400:8400"
        environment:
            ENVIRONMENT: "DEVELOPMENT"
            PG_DSN: "postgresql://bracket_dev:bracket_dev@postgres:5432/bracket_dev"
        restart: unless-stopped
        depends_on:
          - postgres

    postgres:
        image: postgres
        restart: always
        environment:
          POSTGRES_DB: bracket_dev
          POSTGRES_USER: bracket_dev
          POSTGRES_PASSWORD: bracket_dev
```
          
  
![image](https://github.com/evroon/bracket/assets/35930914/d1b450ae-78af-4207-a050-0a74cc79cdba)
![image](https://github.com/evroon/bracket/assets/35930914/48f91a01-6123-43c8-b2a4-85a656138e92)
