### DISCUSSION TITLE
Internal Server Error

### DISCUSSION THREAD

**Discussion by Cyberlytical-LLC** [evroon/bracket#694] [Q&A]
When setting up a new instance of Bracket I get an internal server error when trying to log in. I followed everything from the quickstart and even tried a prod setup with nothing working. 

I have tried on 2 different Ubuntu 22.04 VMs and get the same error. (Vms are on a separate vlan from PC)

When trying to log in I get the following error: 
![Capture](https://github.com/evroon/bracket/assets/108770346/45710599-03fe-4e8d-93dd-96de8f98201b)

I have also tried setting the API url with no luck. It continues to go for localhost. 

Its almost like the env files/ parameters are applying and the base code is borked.

**Comment by furtabs** [comment]
I had better luck with a newer docker version the one from docker's own repos.

and changing DEVELOPMENT to PRODUCTION

Cheers

**Comment by furtabs** [comment]
Actually i did switch back to DEVELOPMENT. Try the updated docker tho from docker's official repos not the ubnutu one with this docker compose file.

```
services:
    bracket-frontend:
        image: ghcr.io/evroon/bracket-frontend
        container_name: bracket-frontend
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_BASE_URL: "http://50.20.249.11:8400"
            # Go to https://dashboard.hcaptcha.com/signup, create a site and put the site key here
            NEXT_PUBLIC_HCAPTCHA_SITE_KEY: "xxxxx"
            NODE_ENV: "production"
        restart: unless-stopped

    bracket-backend:
        image: ghcr.io/evroon/bracket-backend
        container_name: bracket-backend
        ports:
            - "8400:8400"
        environment:
            ENVIRONMENT: "DEVELOPMENT"
            PG_DSN: "postgresql://bracket_dev:bracket_dev@postgres:5432/bracket_dev"
        volumes:
            - ./backend/static:/app/static
        restart: unless-stopped
        depends_on:
          - postgres

    postgres:
        image: postgres
        restart: always
        environment:
          POSTGRES_DB: bracket_prod
          POSTGRES_USER: bracket_prod
          POSTGRES_PASSWORD: bracket_prod
```

Cheers :)
