### DISCUSSION TITLE
Docker not starting

### DISCUSSION THREAD

**Discussion by ereignisgestaltung** [evroon/bracket#755] [Q&A]
Hi,
I'm no pro and I'm trying to get the docker container to run.
Frontend and database seem to work Fine, but the backend container keeps restarting.
Maybe someone can help me understand why?
I also tried the default volumes, but no files are beeing created.

Here is my docker compose:

```
version: '3.1'

services:
    bracket-frontend:
        image: ghcr.io/evroon/bracket-frontend
        container_name: bracket-frontend
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_BASE_URL: "https://bracket.mywebsite.com"
            # Go to https://dashboard.hcaptcha.com/signup, create a site and put the site key here
            NEXT_PUBLIC_HCAPTCHA_SITE_KEY: "xxx"
            NODE_ENV: "production"
        volumes:
          - /home/docker/bracket/frontend:/app/static
        restart: unless-stopped

    bracket-backend:
        image: ghcr.io/evroon/bracket-backend
        container_name: bracket-backend
        ports:
            - "8400:8400"
        environment:
            ENVIRONMENT: "PRODUCTION"
            PG_DSN: "postgresql://bracket_prod:bracket_prod@postgres:5432/bracket_prod"
        volumes:
          - /home/docker/bracket/backend:/app/static
        restart: unless-stopped
        depends_on:
          - postgres

    postgres:
        image: postgres
        restart: always
        environment:
          POSTGRES_DB: bracket_prod
          POSTGRES_USER: bracket_prod
          POSTGRES_PASSWORD: bracket_prod
        volumes:
          - /home/docker/bracket/postgres:/var/lib/postgresql/data
```

And here the error log:
```
bracket-backend     | [2024-06-03 13:55:41 +0000] [1] [INFO] Starting gunicorn 22.0.0
bracket-backend     | [2024-06-03 13:55:41 +0000] [1] [INFO] Listening at: http://0.0.0.0:8400 (1)
bracket-backend     | [2024-06-03 13:55:41 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
bracket-backend     | [2024-06-03 13:55:41 +0000] [9] [INFO] Booting worker with pid: 9
bracket-backend     | [2024-06-03 13:55:42 +0000] [9] [ERROR] Exception in worker process
bracket-backend     | Traceback (most recent call last):
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
bracket-backend     |     worker.init_process()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/uvicorn/workers.py", line 68, in init_process
bracket-backend     |     super().init_process()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
bracket-backend     |     self.load_wsgi()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
bracket-backend     |     self.wsgi = self.app.wsgi()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
bracket-backend     |     self.callable = self.load()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
bracket-backend     |     return self.load_wsgiapp()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
bracket-backend     |     return util.import_app(self.app_uri)
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
bracket-backend     |     mod = importlib.import_module(module)
bracket-backend     |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
bracket-backend     |     return _bootstrap._gcd_import(name[level:], package, level)
bracket-backend     |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
bracket-backend     |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
bracket-backend     |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
bracket-backend     |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
bracket-backend     |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
bracket-backend     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
bracket-backend     |   File "/app/bracket/app.py", line 12, in <module>
bracket-backend     |     from bracket.config import Environment, config, environment, init_sentry
bracket-backend     |   File "/app/bracket/config.py", line 83, in <module>
bracket-backend     |     config = ProductionConfig()  # type: ignore[call-arg]
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/pydantic_settings/main.py", line 71, in __init__
bracket-backend     |     super().__init__(
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/pydantic/main.py", line 176, in __init__
bracket-backend     |     self.__pydantic_validator__.validate_python(data, self_instance=self)
bracket-backend     | pydantic_core._pydantic_core.ValidationError: 1 validation error for ProductionConfig
bracket-backend     | jwt_secret
bracket-backend     |   Field required [type=missing, input_value={'pg_dsn': 'postgresql://...gres:5432/bracket_prod'}, input_type=dict]
bracket-backend     |     For further information visit https://errors.pydantic.dev/2.7/v/missing
bracket-backend     | [2024-06-03 13:55:42 +0000] [9] [INFO] Worker exiting (pid: 9)
bracket-backend     | [2024-06-03 13:55:42 +0000] [1] [ERROR] Worker (pid:9) exited with code 3
bracket-backend     | [2024-06-03 13:55:42 +0000] [1] [ERROR] Shutting down: Master
bracket-backend     | [2024-06-03 13:55:42 +0000] [1] [ERROR] Reason: Worker failed to boot.
bracket-backend     | [2024-06-03 13:55:47 +0000] [1] [INFO] Starting gunicorn 22.0.0
bracket-backend     | [2024-06-03 13:55:47 +0000] [1] [INFO] Listening at: http://0.0.0.0:8400 (1)
bracket-backend     | [2024-06-03 13:55:47 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
bracket-backend     | [2024-06-03 13:55:47 +0000] [9] [INFO] Booting worker with pid: 9
bracket-backend     | [2024-06-03 13:55:47 +0000] [9] [ERROR] Exception in worker process
bracket-backend     | Traceback (most recent call last):
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
bracket-backend     |     worker.init_process()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/uvicorn/workers.py", line 68, in init_process
bracket-backend     |     super().init_process()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
bracket-backend     |     self.load_wsgi()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
bracket-backend     |     self.wsgi = self.app.wsgi()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
bracket-backend     |     self.callable = self.load()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
bracket-backend     |     return self.load_wsgiapp()
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
bracket-backend     |     return util.import_app(self.app_uri)
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
bracket-backend     |     mod = importlib.import_module(module)
bracket-backend     |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
bracket-backend     |     return _bootstrap._gcd_import(name[level:], package, level)
bracket-backend     |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
bracket-backend     |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
bracket-backend     |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
bracket-backend     |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
bracket-backend     |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
bracket-backend     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
bracket-backend     |   File "/app/bracket/app.py", line 12, in <module>
bracket-backend     |     from bracket.config import Environment, config, environment, init_sentry
bracket-backend     |   File "/app/bracket/config.py", line 83, in <module>
bracket-backend     |     config = ProductionConfig()  # type: ignore[call-arg]
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/pydantic_settings/main.py", line 71, in __init__
bracket-backend     |     super().__init__(
bracket-backend     |   File "/home/bracket/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/pydantic/main.py", line 176, in __init__
bracket-backend     |     self.__pydantic_validator__.validate_python(data, self_instance=self)
bracket-backend     | pydantic_core._pydantic_core.ValidationError: 1 validation error for ProductionConfig
bracket-backend     | jwt_secret
bracket-backend     |   Field required [type=missing, input_value={'pg_dsn': 'postgresql://...gres:5432/bracket_prod'}, input_type=dict]
bracket-backend     |     For further information visit https://errors.pydantic.dev/2.7/v/missing
bracket-backend     | [2024-06-03 13:55:47 +0000] [9] [INFO] Worker exiting (pid: 9)
bracket-backend     | [2024-06-03 13:55:47 +0000] [1] [ERROR] Worker (pid:9) exited with code 3
bracket-backend     | [2024-06-03 13:55:47 +0000] [1] [ERROR] Shutting down: Master
bracket-backend     | [2024-06-03 13:55:47 +0000] [1] [ERROR] Reason: Worker failed to boot.
bracket-backend exited with code 3



```

**Comment by djpiper28** [comment]
Looks like you are missing some environment variables.

**Reply by ereignisgestaltung** [reply]
Yes, thanks. I was looking for a file, to add them...
So this is my compose:
```
version: '3.1'

services:
    bracket-frontend:
        image: ghcr.io/evroon/bracket-frontend
        container_name: bracket-frontend
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_BASE_URL: "https://my.website:8400"
            NEXT_PUBLIC_HCAPTCHA_SITE_KEY: "xxx"
            NODE_ENV: "production"
        restart: unless-stopped

    bracket-backend:
        image: ghcr.io/evroon/bracket-backend
        container_name: bracket-backend
        ports:
            - "8400:8400"
        environment:
            ENVIRONMENT: "PRODUCTION"
            PG_DSN: "postgresql://bracket_prod:bracket_prod@postgres:5432/bracket_prod"
            JWT_SECRET: "xxx"
            CORS_ORIGINS: "*"
            ADMIN_EMAIL: "mail@mail.com"
            ADMIN_PASSWORD: "xxxx"
            ALLOW_INSECURE_HTTP_SSO: "false"
        volumes:
            - /home/docker/bracket/backend:/app/static
        restart: unless-stopped
        depends_on:
            - postgres

    postgres:
        image: postgres
        container_name: bracket-postgres
        restart: always
        environment:
            POSTGRES_DB: bracket_prod
            POSTGRES_USER: bracket_prod
            POSTGRES_PASSWORD: bracket_prod
        volumes:
            - /home/docker/bracket/postgres:/var/lib/postgresql/data
```
And this is my Apache config:
```
<IfModule mod_ssl.c>
    <VirtualHost *:8080>
        ServerAdmin webmaster@yourdomain.com
        DocumentRoot /var/www/html
        ServerName xxx

        SSLEngine on
        SSLCertificateFile /etc/letsencrypt/live/xxx/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/xxx/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf

        ProxyPreserveHost On

        # Proxy to backend API
        ProxyPass /api http://localhost:8400/
        ProxyPassReverse /api http://localhost:8400/

        # Proxy to frontend
        ProxyPass / http://localhost:3000/
        ProxyPassReverse / http://localhost:3000/

        Header always set Access-Control-Allow-Origin "*"
        Header always set Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE"
        Header always set Access-Control-Allow-Headers "Authorization, Content-Type"

        # Handle preflight requests
        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{REQUEST_METHOD} OPTIONS
            RewriteRule ^(.*)$ $1 [R=200,L]
        </IfModule>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>
</IfModule>
```
When I try to login I get this error:
`Cross-source (cross-origin) request blocked: The same-source rule prohibits reading the external resource at https://xxx:8400/token. (Reason: CORS request failed). Status code: (null).`

You have any suggestions for me? Tried figuring it out with ChatGPT, but I am stuck...

**Reply by djpiper28** [reply]
So the way I have it setup, albeit with Kubernetes and Nginx which similar, is having the frontend exposed on my domain.

```nginx
server { 
        server_name bracket.example.co.uk;
	listen 443 http2 ssl proxy_protocol;
	listen [::]:443 http2 ssl proxy_protocol;

	ssl_certificate /etc/letsencrypt/live/bracket.example.co.uk/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/bracket.example.co.uk/privkey.pem;

	location / { # The frontend is served here
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto http;

		proxy_pass http://bracket-frontend.default.svc.cluster.local:3000/;
		proxy_read_timeout 5;

		limit_req zone=one burst=20;
	}

	location /api/ { # The api is server on /api/
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto http;

		proxy_pass http://bracket-backend.default.svc.cluster.local:8400/;
		proxy_read_timeout 5;

		limit_req zone=one burst=20;
	}
}
```

With CORs you need to set the domain to the exact one of your frontend, port included. I have set mine to:
```yaml
  - name: CORS_ORIGINS
    value: https://bracket.example.co.uk
  - name: CORS_ORIGIN_REGEX
    value: ^https://bracket.example.co.uk$
```

This is as /api/ is under `https://bracket.example.co.uk` so it works.

Try setting your CORs to `https://yourdomain:8400`
