### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by hibes** [evroon/bracket#1188]
I really hate to bug you with another cors issue since there are so many here, but none of the information in the other tickets is helping me.

None of this stuff is reachable from the net.

My domain: https://bracket.0ti.me
My backend: https://bbracket.0ti.me
Important bits from my docker-compose:

```
services:
  bracket-backend:
    environment:
      ENVIRONMENT: DEVELOPMENT
      CORS_ORIGINS: https://bracket.0ti.me
  bracket-frontend:
    environment:
      NEXT_PUBLIC_API_BASE_URL: https://bbracket.0ti.me
```

![Image](https://github.com/user-attachments/assets/206828da-2341-48e3-9a16-72313ac2c1b2)

A side note, something's wrong with the way the `CORS_ORIGIN_REGEX` gets loaded because `'.*'` ends up resolving paths erroneously resulting in a string `'. ..'`.
