### ISSUE TITLE
can't run behind traefik proxy

### ISSUE THREAD

**Issue by homa8511** [evroon/bracket#574]
starting bracket in docker behind traefik leads to bracket-frontend quitting with error code 1. 

A lot of log spam like this:

```
bracket-frontend  | Checking that we have variables...
bracket-frontend  | 
bracket-frontend  | # Script to replace `NEXT_PUBLIC_*` environment variables because they're set at build-time but we want to set them at runtime in `docker-compose.yml`
bracket-frontend  | # Define an array of environment variable names
bracket-frontend  | env_vars=("NEXT_PUBLIC_API_BASE_URL" "NEXT_PUBLIC_HCAPTCHA_SITE_KEY")
bracket-frontend  | 
bracket-frontend  | echo "Checking that we have variables..."
bracket-frontend  | # Iterate over the array and perform checks
bracket-frontend  | for var in "${env_vars[@]}"; do
bracket-frontend  |   test -n "${!var}"
bracket-frontend  | done
bracket-frontend  | 
```

and finally:
```
bracket-backend   | [2024-02-29 14:36:37,752] [bracket] [INFO] Current env: PRODUCTION
bracket-backend   | [2024-02-29 14:36:37,772] [bracket] [INFO] Current env: PRODUCTION
bracket-backend   | [2024-02-29 14:36:38 +0000] [10] [INFO] Started server process [10]
bracket-backend   | [2024-02-29 14:36:38 +0000] [10] [INFO] Waiting for application startup.
bracket-frontend exited with code 1
bracket-backend   | [2024-02-29 14:36:39 +0000] [9] [INFO] Started server process [9]
bracket-backend   | [2024-02-29 14:36:39 +0000] [9] [INFO] Waiting for application startup.
bracket-backend   | [2024-02-29 14:36:39,353] [bracket] [INFO] Running migrations
bracket-backend   | [2024-02-29 14:36:39 +0000] [10] [INFO] Application startup complete.
bracket-backend   | [2024-02-29 14:36:39,486] [bracket] [INFO] Running migrations
bracket-backend   | [2024-02-29 14:36:39 +0000] [9] [INFO] Application startup complete.
bracket-frontend exited with code 1
bracket-frontend exited with code 1
bracket-frontend exited with code 1
bracket-frontend exited with code 1
bracket-frontend exited with code 1
bracket-frontend exited with code 1
bracket-frontend exited with code 1
docker-compose.yml
```

**docker-compose.yml**
```
version: '3.1'

services:
  bracket-frontend:
    image: ghcr.io/evroon/bracket-frontend
    container_name: bracket-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "https://bracket.mydomain.com"
      # Go to https://dashboard.hcaptcha.com/signup, create a site and put the site key here
      NEXT_PUBLIC_HCAPTCHA_SITE_KEY: ""
      NODE_ENV: "production"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bracket.entrypoint=websecure"
      - "traefik.http.routers.bracket.rule=Host(`bracket.mydomain.com`)"
      - "traefik.http.routers.bracket.middlewares=default@file"
      - "traefik.http.routers.bracket.tls=true"
      - "traefik.http.routers.bracket.tls.certresolver=tls_resolver"
      - "traefik.http.routers.bracket.service=bracket"
      - "traefik.http.services.bracket.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default

  bracket-backend:
    image: ghcr.io/evroon/bracket-backend
    container_name: bracket-backend
    ports:
      - "8400:8400"
    environment:
      ENVIRONMENT: "PRODUCTION"
      PG_DSN: "postgresql://bracket_prod:bracket_prod@bracket-db:5432/bracket_prod"
      JWT_SECRET: "MY_SECRET_KEY"
      CORS_ORIGINS: "https://bracket.mydomain.com"
      ALLOW_INSECURE_HTTP_SSO: "false"
      ADMIN_EMAIL: "my@adm.in"
      ADMIN_PASSWORD: "MY_SECRET_PW"
    restart: unless-stopped
    depends_on:
      - bracket-db
    networks:
      - default

  bracket-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bracket_prod
      POSTGRES_USER: bracket_prod
      POSTGRES_PASSWORD: bracket_prod
    networks:
      - default

networks:
  proxy:
    external: true
```
